server:
  servlet:
    context-path: '/university/'

spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1'
    username: 'sa'
    password: 'sa'
    driver-class-name: org.h2.Driver
  flyway:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1"
    user: "sa"
    password: "sa"
    locations: local
    baseline-on-migrate: true
  data:
    mongodb:
      authentication-database: admin
      username: docker
      password: mongopw
      database: test_history
      port: 27017
      host: localhost
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
jwt:
  header: Authorization
  expires: 604800