server:
  servlet:
    context-path: '/university/'

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/university'
    username: 'natanius'
    password: '12345'
    driver-class-name: org.postgresql.Driver
  flyway:
    url: "jdbc:postgresql://localhost:5432/university"
    user: "natanius"
    password: "12345"
  jpa:
    properties:
      hibernate:
        dialect=org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      authentication-database: admin
      username: docker
      password: mongopw
      database: test_history
      port: 27017
      host: localhost
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092

  flyway.baseline-on-migrate: true

jwt:
  header: Authorization
  expires: 604800